### ISSUE TITLE
Pin asyncssh to >=2.7.0,<2.8.0 version

### ISSUE THREAD

**Issue by mp24-git** [iterative/sshfs#10]
Currently, SSHFS is pinned to asyncssh==2.7.0. There are some smaller issues solved in 2.7.2, which I cannot install "normally" via pip. I can only install SSHFS first, then upgrade asyncssh, ignoring the resolver warnings.

2.7.2 contains some fixes for specific SSH/SFTP servers (https://github.com/ronf/asyncssh/blob/develop/docs/changes.rst#release-272-15-sep-2021).

I suggest pinning to `asyncssh>=2.7.0,<2.8.0` or `asyncssh>=2.7.0`

**Comment by efiop** [comment]
@mp24-git 2021.11.0 is out on pypi, please upgrade and give it a try. Thanks for the feedback! 🙏

**Comment by mp24-git** [comment]
@efiop Many many thanks. Now, pip can install latest asyncssh in combination with sshfs.
